### ISSUE TITLE
Profile and export errors

### ISSUE THREAD

**Issue by Nastras** [SumolX/FlashForge#1]
Hello, thanks in advance for your work.

I wanted to try your script today with the SuperSlicer without Phyton. To my knowledge SuperSlicer is an extension of PrusaSlicer and it should actually work. Or am I seeing this wrong?

Unfortunately I get an error once in the AD Fine profile. See picture. 

Also, I can't export G-code because it stops with an error. See picture.
I have tried different memory locations. The error is the same.

Do you have any idea why?

![Screenshot 2022-06-30 181120](https://user-images.githubusercontent.com/27686185/176727536-cae3b046-3e23-45f7-8919-77feedfba324.jpg)
![Screenshot 2022-06-30 181220](https://user-images.githubusercontent.com/27686185/176727544-97f22881-8a0a-49bb-95d3-c1aa6b0f1e2b.jpg)

**Comment by SumolX** [comment]
PrusaSlicer and Slic3r under the hood use different variable names....  this script is not compatible with Slic3r.

I imagine the same applies to the config bundle.

**Comment by Nastras** [comment]
Thanks for the quick reply. Is it possible that you support Superslicer?

**Comment by SumolX** [comment]
I would have to look into it.... but at the same time I would have to make many prints to ensure the settings are correct.... and I'm not sure I want to invest that amount of filament since I am happy with PrusaSlicer

**Comment by Nastras** [comment]
Ok, I did not know that it is so elaborate. Maybe you can just customize it so that it basically works with SupeSlicer without having to test every setting yourself?

Do you think that Prusa Slicer and SuperSlicer are so different?

**Comment by Nastras** [comment]
I have now installed Prusa Slicer. The error has remained the same.

Looks like the problem is not caused by the software. Do you have any idea?

**Comment by Nastras** [comment]
![Screenshot 2022-07-03 064629](https://user-images.githubusercontent.com/27686185/177025251-fc6f568a-a957-4b4d-a496-10cebd1ae66a.jpg)

**Comment by Nastras** [comment]
![Screenshot 2022-07-03 064734](https://user-images.githubusercontent.com/27686185/177025262-5f2b3e2e-60ef-4695-8186-81a192fafdaf.jpg)

**Comment by Nastras** [comment]
![Uploading Screenshot 2022-07-03 064803.jpg…]()

**Comment by Nastras** [comment]
![Screenshot 2022-07-03 064803](https://user-images.githubusercontent.com/27686185/177025287-a917a285-8909-43ab-8d7e-639b75586252.jpg)

**Comment by SumolX** [comment]
Let's first try without the FlashForgeAdapter.exe and see if it generates a gx file.  Remove the entire line on the bottom box.  Attach the file so I can review it in my setup.

**Comment by Nastras** [comment]
I have now tried it without the line.
 A file.gx is created.
![Screenshot 2022-07-03 155951](https://user-images.githubusercontent.com/27686185/177043201-6aaf7676-b531-4bb3-802a-60ecb584d5fb.jpg)

**Comment by Nastras** [comment]
I have now tried many things, unfortunately all without success. As a sample I have tested the original script from Don. This works perfectly.

It looks somehow as if for this the authorizations are missing:
C: \Users\famil\ AppData\Loca/\Temp\.15064.gcode.pp

I can't think of anything else I can't do.

**Comment by SumolX** [comment]
Please upload your gx file so I can test it on my setup.

And make sure you can access that directory too

**Comment by SumolX** [comment]
When I create the python script I used PyInstaller which creates the executable.  Perhaps there is a dependency missing.....

**Comment by SumolX** [comment]
In the gx file what does the following field contain:

;filename:

**Comment by Nastras** [comment]
Here is the gx file.
https://ucarecdn.com/3e202b57-2d43-4791-bfef-b82a0e30ed1c/

**Comment by Nastras** [comment]
;filename: Leveltest 1.gx

**Comment by Nastras** [comment]
I don't have Python on my Windows PC. I acted according to your instructions for Windows (No Python Environment).

Or do you mean there is a dependency missing to make it work on windows without python?

**Comment by Nastras** [comment]
A small note. When I slice the file, your tool opens briefly and I see a black window for a very short time. After that comes the error message shown above.

**Comment by Nastras** [comment]
I have now made some progress in narrowing down the error.

If I only enter this line, your tool works and a gcode with image is created.

c:\path\to\executable\FlashForgeAdapter\FlashForgeAdapter.exe


As it looks it is the automatic import to Flashprint that generates the error.

--ffslicer="C:\Program Files\FlashForge\FlashPrint 5\FlashPrint.exe"


At least it works now ;-)

**Comment by Nastras** [comment]
Here is the new gx file:
https://ucarecdn.com/aec8bdb8-e061-4396-b868-c7bf8a1a7556/

**Comment by SumolX** [comment]
I can reproduce the error... I will fix it.

**Comment by Nastras** [comment]
👌💪👍

**Comment by SumolX** [comment]
It's a silly bug with the exe version... if you remove the space from the filename: leveltest 1.gx -> leveltest_1.gx it will forward it properly to FlashPrint.

**Comment by SumolX** [comment]
I pushed up the fix.  Let me know if it works now with filenames that contain spaces.

**Comment by Nastras** [comment]
The auto export still does not work for me. I have completely replaced the files from the script. The error is the same. No matter if the file has a space or not.

I say so the function is not very important for me. I can also import to Flashprint manually.

But I wanted to share it with you ;-)

Here again my path:
"C:\Users\famil\Desktop\XXXXX\ scripts\FlashForgeAdapter\FlashForgeAdapter.exe" --ffslicer="C:\Programs (x86)\FlashForge\FlashPrint 5\FlashPrint.exe";

**Comment by SumolX** [comment]
Just want to be sure.... there should be no quotes around the FlashForgeAdapter.exe

Quotes are only needed for --ffslicer=""

But you obviously got it to work without the ffslicer parameter.

Strange because it was able to reproduce an error with spaces....  maybe your error is different.... maybe because your windows is using a different language installation.... I have no idea why it's behaving differently.

But you are able to use it and everything else is working.... thumbnail..... etc
